### ISSUE TITLE
Project links on the homepage are broken

### ISSUE THREAD

**Issue by nathanielw** [samselikoff/samselikoff.github.io#9]
Looks like they're using `project.project_url` instead of `project.link`

**Comment by samselikoff** [comment]
Sorry, I'm not sure what you mean. Which homepage?

**Comment by nathanielw** [comment]
http://www.samselikoff.com/
The individual links in the _Code + Design_ box.

**Comment by samselikoff** [comment]
Ah, thank you - fixed!
